name: AI News Notifier

on:
  schedule:
    # 毎日午前9時（UTC）に実行（日本時間18時）
    - cron: '0 9 * * *'
  workflow_dispatch: # 手動実行も可能にする

jobs:
  fetch-and-notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests groq
        
    - name: Run AI News Notifier
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: python ai_news_notifier.py
